# Be sure to restart your server when you modify this file.
#
# This file contains migration options to ease your Rails 6.0 upgrade.
#
# Once upgraded flip defaults one by one to migrate to the new default.
#
# There is no stock Rails 6.0 template for this app to inherit (the upgrade
# jumped 5.2 -> 6.1 directly, skipping 6.0), so this file was hand-authored
# from the `load_defaults("6.0")` case branch in the installed railties gem
# (railties-6.1.7.10/lib/rails/application/configuration.rb) rather than
# generated by `rails app:update`. It only lists the settings from that case
# branch -- it intentionally omits `self.autoloader = :zeitwerk`, since that
# switch is being decided on explicitly and separately (see upgrade notes),
# not flipped one-by-one like the settings below.

# Framework will no longer add a hidden UTF8-enforcer input to every form --
# harmless, all modern browsers already submit UTF-8 regardless.
Rails.application.config.action_view.default_enforce_utf8 = false

# Embed purpose and expiry metadata inside signed and encrypted cookies for
# increased security.
#
# Not backwards compatible with earlier Rails versions in general, but this
# app has no production traffic yet on this branch (still mid-upgrade, not
# deployed), so there are no live cookies this needs to stay compatible with.
Rails.application.config.action_dispatch.use_cookies_with_metadata = true

# Use the newer, more full-featured ActionMailer::MailDeliveryJob for
# `deliver_later` instead of ActionMailer::DeliveryJob. This app has no
# `deliver_later` call sites today, so this is currently dormant either way.
Rails.application.config.action_mailer.delivery_job = "ActionMailer::MailDeliveryJob"

# Set the default queue name for the analysis job to the queue adapter
# default. This app doesn't use Active Storage attachments today.
Rails.application.config.active_storage.queues.analysis = :active_storage_analysis

# Set the default queue name for the purge job to the queue adapter default.
Rails.application.config.active_storage.queues.purge = :active_storage_purge

# When assigning to a collection of attachments, replace them instead of
# appending. See https://guides.rubyonrails.org/active_storage_overview.html
# #adding-attachments-to-a-record for more information.
Rails.application.config.active_storage.replace_on_assign_to_many = true

# Use ActiveSupport::Digest for generating cache versions along with cache
# keys, avoiding recomputation of cache versions on each request.
Rails.application.config.active_record.collection_cache_versioning = true
